var files_dup =
[
    [ "admin.cpp", "admin_8cpp.html", null ],
    [ "admin.h", "admin_8h.html", "admin_8h" ],
    [ "adminaddsouvenir.cpp", "adminaddsouvenir_8cpp.html", null ],
    [ "adminaddsouvenir.h", "adminaddsouvenir_8h.html", "adminaddsouvenir_8h" ],
    [ "adminchangeprice.cpp", "adminchangeprice_8cpp.html", null ],
    [ "adminchangeprice.h", "adminchangeprice_8h.html", "adminchangeprice_8h" ],
    [ "admindeletesouvenir.cpp", "admindeletesouvenir_8cpp.html", null ],
    [ "admindeletesouvenir.h", "admindeletesouvenir_8h.html", "admindeletesouvenir_8h" ],
    [ "basictripwindow.cpp", "basictripwindow_8cpp.html", null ],
    [ "basictripwindow.h", "basictripwindow_8h.html", "basictripwindow_8h" ],
    [ "customtripwindow.cpp", "customtripwindow_8cpp.html", null ],
    [ "customtripwindow.h", "customtripwindow_8h_source.html", null ],
    [ "login.cpp", "login_8cpp.html", null ],
    [ "login.h", "login_8h.html", "login_8h" ],
    [ "main.cpp", "main_8cpp.html", null ],
    [ "mainwindow.cpp", "mainwindow_8cpp.html", null ],
    [ "mainwindow.h", "mainwindow_8h.html", "mainwindow_8h" ],
    [ "modcolleges.cpp", "modcolleges_8cpp.html", null ],
    [ "modcolleges.h", "modcolleges_8h.html", "modcolleges_8h" ],
    [ "modsouvenirs.cpp", "modsouvenirs_8cpp.html", null ],
    [ "modsouvenirs.h", "modsouvenirs_8h.html", "modsouvenirs_8h" ],
    [ "summarywindow.cpp", "summarywindow_8cpp.html", null ],
    [ "summarywindow.h", "summarywindow_8h.html", "summarywindow_8h" ],
    [ "tripwindow.cpp", "tripwindow_8cpp.html", null ],
    [ "tripwindow.h", "tripwindow_8h.html", "tripwindow_8h" ]
];